# Generated by Django 4.2.7 on 2023-11-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='curs',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='facultet',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nom_tel',
        ),
        migrations.RemoveField(
            model_name='person',
            name='obrazov_pr',
        ),
        migrations.RemoveField(
            model_name='person',
            name='osebe',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rabota',
        ),
        migrations.RemoveField(
            model_name='person',
            name='student',
        ),
        migrations.RemoveField(
            model_name='person',
            name='stupen_obrazov',
        ),
        migrations.RemoveField(
            model_name='person',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='person',
            name='users_photo',
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
